##this code generates the subfigure 2c

import matplotlib.pyplot as plt
import numpy as np

x1,y1 = np.loadtxt('height_slow_eta_0.225_kf_4_19_cu_gel_0.6_step1_refined_mesh.csv',delimiter=',',unpack=True) #generated by postprocessing the deform.pvd file which is the output of weak_acid_1d_step_1.py in Paraview 5.7.0 to create a height profile
x4,y4 = np.loadtxt('height_slow_eta_0.225_kf_4_19_cu_gel_0.6_step2_refined_mesh.csv',delimiter=',',unpack=True)#generated by postprocessing the deform.pvd file which is the output of weak_acid_1d_step_2.py in Paraview 5.7.0 to create a height profile
x3,y3 = np.loadtxt('height_experimental_data_slow_step1.csv',delimiter=',',unpack=True)#tilt angle profile from experiments for weak acid addition
x21, y21 = np.loadtxt('slow_height_avg_2d_1.txt', unpack=True, comments='%')#2d gel height average for the addition of 0.01M acid genrated from weak_acid_2D.mph.Please look at Derived values-Hydrogel height 0.01M in weak_acid_2D.mph. 
x22, y22 = np.loadtxt('slow_height_avg_2d_2.txt', unpack=True, comments='%')#2d gel height average for the addition of 0.05M acid genrated from weak_acid_2D.mph. Please look at Derived values-Hydrogel height 0.05M in weak_acid_2D.mph. 
x2 = np.concatenate((x21,x22))
y2 = np.concatenate((y21,y22))

y3 = np.radians(y3)
y3 = np.cos(y3)
y3 = y3/np.cos(np.radians(9))

x3[22:] = x3[22:]-9
print(x3)

x4 = x4+8.4
fig,ax = plt.subplots()

#axis linewidth
for axis in ['top','bottom','left','right']:
    ax.spines[axis].set_linewidth(2)

#tick parameters
ax.tick_params(axis="x", direction = "in", length=10, width=2, labelsize=32)
ax.tick_params(axis="y", direction = "in", length=10, width=2, labelsize=0.0, labelcolor = "white")

#tick labels
ax.xaxis.set_ticks(np.arange(0.,28.1,7))
ax.yaxis.set_ticks(np.arange(0.9,1.01,0.05))

#plotting experimental data
x3 = x3/2.5
ax.scatter(x3[::2],y3[::2],color="black",marker='o', s=140,zorder=2.5, facecolor='none', linewidths=3)

#plotting 1d gel height
ax.plot(x2,y2, color='blue', linewidth='5')
ax.plot(x1,y1,color='black',linewidth='5')
ax.plot(x4,y4,color='black',linewidth='5')

ax.set_ylim(0.9,1.01)
ax.set_xlim(-1,28.1)

plt.savefig('height_slow_eta_0.225_kf_4_19_cu_gel_0.6.png', dpi=300,bbox_inches='tight', pad_inches=0.0)
plt.show()
